[build]
  # The build command that Netlify will run
  command = "npm run build"
  
  # The directory to publish after the build process
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
